//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2084_a2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class assm2Entities : DbContext
    {
        public assm2Entities()
            : base("name=assm2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<author> authors { get; set; }
        public virtual DbSet<book> books { get; set; }
        public virtual DbSet<genre> genres { get; set; }
        public virtual DbSet<review> reviews { get; set; }
        public virtual DbSet<Table> Tables { get; set; }
        public virtual DbSet<time> times { get; set; }
        public virtual DbSet<title> titles { get; set; }
    }
}
