//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2084_a2
{
    using System;
    using System.Collections.Generic;
    
    public partial class book
    {
        public int bookId { get; set; }
        public string title { get; set; }
        public string genre { get; set; }
        public string time { get; set; }
        public string author { get; set; }
        public string review { get; set; }
    }
}
