//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2084_a2
{
    using System;
    using System.Collections.Generic;
    
    public partial class time
    {
        public int timeId { get; set; }
        public string time1 { get; set; }
        public int bookId { get; set; }
    }
}
